int RandMoore(int k, int x, int y);
int Moore(int k, int x, int y);
int CountMoore(int k, int n, int x, int y);
int RandVonn(int k, int x, int y);
int Vonn(int k, int x, int y);
int CountVonn(int k, int n, int x, int y);
void CopyLayer(int k, int l);
void AsynTorus(int x, int y);
void AsynEcho(int x, int y);
void TorusLayer(int k);
void RecordGrowth(int k,int spec);
void InitRandomLayer(int k);
void ReShuffle(int k);
void DiffuseStop(int k,int l);
void Diffuse(int k);
void SetBoundaries(int k);
void TurnLeft(int k, int x, int y);
void DoTurn(int k, int x, int y);
void TurnRight(int k, int x, int y);
void DoTurnTogether(int k1, int k2, int x, int y);